### ISSUE TITLE
pretty.Compare can result in unexpected type coercion

### ISSUE THREAD

**Issue by szabado** [kylelemons/godebug#21]
There's some unexpected type coercion that can happen when comparing maps.

```
package main

import (
	"testing"

	"github.com/kylelemons/godebug/pretty"
)

func TestDiffStringKey(t *testing.T) {
	intKey := map[interface{}]interface{}{
		int(123): "abc",
	}

	stringKey := map[interface{}]interface{}{
		"123": "abc",
	}

	diff := pretty.Compare(intKey, stringKey)
	if len(diff) == 0 {
		t.Fatal("No diff found")
	}
}

func TestDiffFloatKey(t *testing.T) {
	intKey := map[interface{}]interface{}{
		int(123): "abc",
	}

	floatKey := map[interface{}]interface{}{
		float64(123.0): "abc",
	}

	diff := pretty.Compare(intKey, floatKey)
	if len(diff) == 0 {
		t.Fatal("No diff found")
	}
}
```

Both of these tests will fail. Given the below test also fails, I'm not sure how trivial this will be to correct.

```
func TestDiffFloat(t *testing.T) {
	diff := pretty.Compare(int(123), float64(123.0))
	if len(diff) != 0 {
		t.Fatal("No diff found")
	}
}
```

Fixing the first test should be as simple as quoting strings when they're map keys. The second one might require actual type comparison, I'm unsure.

**Comment by kylelemons** [comment]
Thanks for the report, Felix!

This is working as intended.  The "Compare" function is quite deliberately diffing against the pretty representation of a value, rather than recursively comparing types.  This can be very convenient, as it can allow you to use a more compact or test-table-readable representation to compare against a value you're getting out of a function, for example.

I definitely agree that this is not ideal if you need to ensure that types are identical when the compiler can't help you out.  For those cases, I recommend [cmp](https://godoc.org/github.com/google/go-cmp/cmp) or [spew](https://godoc.org/github.com/davecgh/go-spew/spew).

Sorry for the trouble!

**Comment by szabado** [comment]
I think it'd be nice to have some comment to this effect in the godoc? At least about the type coercion part, as the docs just say:
> Compare returns a string containing a line-by-line unified diff of the values in a and b, using the CompareConfig.

Which reads either way to me, depending on what you expect.

**Comment by kylelemons** [comment]
OK, I have noted this difference.  Thanks for the suggestion.
