### ISSUE TITLE
Special treatment for net.IP?

### ISSUE THREAD

**Issue by vincentbernat** [kylelemons/godebug#8]
Hey!

`net.IP` is a bit annoying because:
1. it gets printed on several lines
2. it can uses two different representations

For the second point, `net.ParseIP()` will provide something like `0,0,0,0,0,0,0,0,0,0,255,255,192,0,2,12` (this is the IPv4-mapped IPv6 address). But one can also just get `192,0,2,12`.

For me, it would be convenient if pretty could have a special case for IP by using its string representation. Of course, this would make an horrible special-case and maybe you don't want something like that.

Setting `PrintStringers` would defeat much of my use of the pretty printer since the string value is incomplete for most of my types. Maybe provide a list of types that should call String() if available?

**Comment by kylelemons** [comment]
Yes, I have run into this myself as well.  My vague plan to solve it was to have a whitelist `StringifyType map[reflect.Value]bool` in addition to (and overriding, in either case) `PrintStringers`.  I haven't implemented it yet, though, so if you want to take a crack at it, and don't mind [signing the Google CLA](https://cla.developers.google.com/clas), feel free :).  Otherwise, let me know if that solution sounds good to you, and I may be able to find time to bang it out.

**Comment by vincentbernat** [comment]
Yes, that would fit my need too. As for the CLA, for some reason, despite my regular email being registered as an alternate address, the CLA app insists on only using my GMail address that I don't use anywhere.
